String s_favicon=
"<svg  id='favicon' viewBox='-32 -32 64 64' height='64' xmlns='http://www.w3.org/2000/svg' >"
" <rect x='-16' y='-32' width='32' height='64' fill='red' />"
" <rect x='-14' y='-30' width='28' height='16' fill='white' />"
" <circle cx='-8' cy='20' r='4' fill='gold' />"
" <circle cx= '0' cy='24' r='4' fill='black' />"
" <circle cx=' 8' cy='20' r='4' fill='orange' />"
"</svg>"
;

String s_css=
"html{background:black; color:gold; text-align:center;}"
"svg {background:black;}"
;

String s_html_template=
"<!DOCTYPE html><html><head>"
	"<meta charset='utf-8' />"
	"<!--meta http-equiv='refresh' content='10;' -->"
	"<link rel='shortcut icon' href='favicon.ico'>"
	"<link rel='stylesheet'    href='_css/style.css' />"
	"<title>ANENG V05B DMM</title>"
"</head><body>"
"<h1>ANENG V05B DMM"
"<svg  id='favicon' viewBox='-32 -32 64 64' height='64' xmlns='http://www.w3.org/2000/svg' >"
	"<rect x='-16' y='-32' width='32' height='64' fill='red' />"
	"<rect x='-14' y='-30' width='28' height='16' fill='white' />"
	"<circle cx='-8' cy='20' r='4' fill='gold' />"
	"<circle cx= '0' cy='24' r='4' fill='black' />"
	"<circle cx=' 8' cy='20' r='4' fill='orange' />"
	"<text font-size='12' font-family='Consolas' x='-14' y='-18'>1234</text>"
"</svg></h1>"
"<svg viewBox='-512,-978 1024,1080' width='512'>"
	"<g fill='none' stroke-width='3'>"
		"<rect x='-510' y='-978' rx='15' ry='15' width='1020' height='542' fill='#202020' stroke='white' stroke-width='1' />"
		"<rect x='-510' y='-426' rx='15' ry='15' width='1020' height='512' fill='#202020' stroke='white' stroke-width='1' />"
		"<path d='M-392,-668A780,780 0 0 1 392,-668' stroke='red'  stroke-width='11' />"
		"<path d='M-444,-736A860,860 0 0 1 444,-736' stroke='blue' stroke-width='11' />"
	"<path id='dmmptr' fill='red' stroke='none' transform='rotate(-30)' d='M0,0v-820l10,40h-20l10,-40' stroke='aqua' />"
	"</g>"
	"<g text-anchor='middle' font-family='Consolas'>"
		"<text font-size='256'id='dmmtxt' fill='yellow' x='0' y='-500' >12.34</text>"
		"<text font-size='64' id='dmmpre' fill='yellow' x='420' y='-600' >kilo</text>"
		"<text font-size='64' id='dmmuni' fill='yellow' x='420' y='-550' >Ohm</text>"
	"</g>"
	"<g transform='translate(-500,92)'><path id='dmmgraf' stroke='magenta' stroke-width='3'; fill='none' d='M0,-512' /></g>"
"</svg>"
"<script src='myfunc.js'></script>"
"</body></html>"
;
String s_jsfunc=
"var x=0;"
"var vmax=10;"
"var zoom=0.02;"
"var debug=false;"
"s_DmmVal='',s_DmmOpt='',s_DmmPre='micro',s_DmmUnit='Farad';\n"
"function decode_s7(segm)"
"{"
	"if(segm>127){if(s_DmmVal==''){s_DmmVal='-';}else{s_DmmVal+='.';}}"
	"segm=segm & 0x7f;"
	"if(segm==0)   {s_DmmVal+=' '; return;}"
	"if(segm==0x7d){s_DmmVal+='0'; return;}"
	"if(segm==0x05){s_DmmVal+='1'; return;}"
	"if(segm==0x5b){s_DmmVal+='2'; return;}"
	"if(segm==0x1f){s_DmmVal+='3'; return;}"
	"if(segm==0x27){s_DmmVal+='4'; return;}"
	"if(segm==0x3e){s_DmmVal+='5'; return;}"
	"if(segm==0x7e){s_DmmVal+='6'; return;}"
	"if(segm==0x15){s_DmmVal+='7'; return;}"
	"if(segm==0x7f){s_DmmVal+='8'; return;}"
	"if(segm==0x3f){s_DmmVal+='9'; return;}"
	"if(segm==0x77){s_DmmVal+='A'; return;}"
	"if(segm==0x4c){s_DmmVal+='u'; return;}"
	"if(segm==0x6a){s_DmmVal+='t'; return;}"
	"if(segm==0x4e){s_DmmVal+='o'; return;}"
	"if(segm==0x68){s_DmmVal+='L'; return;}"
	// "s_DmmVal+='_'+segm.toString(16)+'_';\n" 
"}\n"
"function decode_flags()"
"{"
	"s_DmmPre=''; s_DmmUnit='';"
	"if(ai_dmm[3] & 0x40){s_DmmOpt+= 'HOLD '; }"
	"if(ai_dmm[7] & 0x01){s_DmmOpt+= 'BT ';  }"
	"if(ai_dmm[8] & 0x80){s_DmmPre+= 'nano';  }"
	"if(ai_dmm[8] & 0x40){s_DmmUnit+='Volt';  }"
	"if(ai_dmm[8] & 0x20){s_DmmOpt+= '( )';   } //?\n"
	"if(ai_dmm[8] & 0x10){s_DmmOpt+= 'BT ';   } //?\n"
	"if(ai_dmm[8] & 0x08){s_DmmUnit+='Farad'; }"
	"if(ai_dmm[8] & 0x04){s_DmmOpt+= ' -|>- ';}"
	"if(ai_dmm[8] & 0x02){s_DmmOpt+= '? ';  } //? \n"
	"if(ai_dmm[8] & 0x01){s_DmmPre+= 'micro'; }"
	"if(ai_dmm[9] & 0x80){s_DmmUnit+='Ohm';   }"
	"if(ai_dmm[9] & 0x40){s_DmmPre+= 'kilo';  }"
	"if(ai_dmm[9] & 0x20){s_DmmPre+= 'milli'; } // ?\n"
	"if(ai_dmm[9] & 0x10){s_DmmPre+= 'Mega';  }"
	"if(ai_dmm[9] & 0x08){s_DmmUnit+='Ampere';} // ?\n"
	"if(ai_dmm[9] & 0x04){s_DmmUnit+='Hz';    }"
	"if(ai_dmm[9] & 0x02){s_DmmUnit+='´F';    }"
	"if(ai_dmm[9] & 0x01){s_DmmUnit+='´C';    }"
	"if(s_DmmVal=='Auto'){s_DmmPre+='Auto';}"
"}\n"
"function msb(lsb)"
"{"
	"mm=128,ml=1,b=0;"
	"for(bi=0;bi<8;bi++){if((lsb & mm)==mm){b+=ml;} mm>>=1; ml<<=1;}"
	"return b;"
"}\n"
"function setdmm(v)"
"{"
	"if(isNaN(v)){return;}"
	"if(v>vmax){vmax=v;}" 
	"deg=-30+60.0*(v/vmax);"
  "console.log(v,vmax,deg);"
	"rotv='rotate('+deg+')';"
	"y=Math.floor(-v/zoom);"
	"document.getElementById('dmmptr').setAttribute('transform',rotv);"
"//	document.getElementById('dmmtxt').textContent=v;\n"
	"d='L'+x+','+y; x++; if(x>1000){x=0;}"
	"eidgraf=document.getElementById('dmmgraf');"
	"eidgraf.setAttribute('d',eidgraf.getAttribute('d')+d);"
"}\n"
"function decode(s_raw)"
"{"
  "if(s_raw.substr(0,5)!='1b 84'){console.log('Invalid',s_raw); return;}"
	"ai_dmmraw=[0,0,0,0,0,0,0,0,0,0];"
	"ai_xorkey=[0x41,0x21,0x73,0x55,0xA2,0xC1,0x32,0x71,0x66,0xAA];"
	"ai_dmmlsb=[0,0,0,0,0,0,0,0,0,0];"
	"ai_seg7  =[0,0,0,0];"
	"ai_dmm   =[0,0,0,0,0,0,0,0,0,0];"
	"s_xor=''; s_lsb=''; s_msb=''; s_seg7='';"
  "for(i=0;i<10;i++)"
	"{"
		"ai_dmmraw[i]=parseInt(s_raw.substr(3*i,2),16);"
		"ai_dmmlsb[i]=ai_dmmraw[i] ^ ai_xorkey[i];"
		"ai_dmm[i]=msb(ai_dmmlsb[i]);"
		"s_xor+=ai_xorkey[i].toString(16)+' ';"
		"s_lsb+=ai_dmmlsb[i].toString(16)+' ';"
		"s_msb+=ai_dmm[i].toString(16)+' ';"
	"}\n"
	"s_DmmVal='';"
	"for(i=0;i<4;i++)"
	"{"
		"ai_seg7[i]=16*(ai_dmm[i+3]%16)+(ai_dmm[i+4]>>4);"
		"decode_s7(ai_seg7[i]);"
		"s_seg7+=ai_seg7[i].toString(16)+' ';"
	"}\n"
	"decode_flags();"
	"console.log(s_raw);"
	"console.log(s_xor);"
	"console.log(s_lsb);"
	"console.log(s_msb);"
	"console.log(s_seg7);"
	"console.log(s_DmmVal,s_DmmPre+s_DmmUnit);"
	"document.getElementById('dmmtxt').textContent=s_DmmVal;"
	"document.getElementById('dmmpre').textContent=s_DmmPre;"
	"document.getElementById('dmmuni').textContent=s_DmmUnit;"
	"setdmm(parseFloat(s_DmmVal));"
"}\n"
"var connection = new WebSocket('ws://%ip%:%port%/');\n"
	"connection.onopen    = function()     { connection.send('Connect ' + new Date());};\n"
	"connection.onerror   = function(error){ console.log('WebSocket Error ', error);};\n"
	"connection.onmessage = function(e)    { console.log('WebSocket RECV ', e.data); decode(e.data);}\n"
	"connection.onclose   = function()     { console.log('WebSocket connection closed');};\n"
;
String s_wsclt=
"<!DOCTYPE html>"
"<html><head>"
  "<meta charset='utf-8' />"
  "<style>html{background:black; color:white;} h1{display:inline;} .err{background:red; color:white;}</style>"
  "<title>WebSock client</title>"
"</head><body>"
"<h1>WebSockClient</h1><br/>"
"Socket:<b><span id='urlws'></span></b><br/>"
"Status:<span id='wsstate'>Connecting..</span> <span id='wserr' class='err'> undef </span>"
"<hr/>"
"<button onclick=document.getElementById('wslog').innerHTML='';>Clear Log</button>"
"&nbsp; <span id='wscnt'>0</span> Packets received<br/>"
"<textarea id='wslog' cols='32' rows='80'></textarea>"
"<script>\n"
"var ip='%ip%';\n"
"var port='%port%';\n"
"var wsurl='ws://'+ip+':'+port+'/';"
"var i_cnt=0;"
"document.getElementById('urlws').innerHTML=wsurl;"
"eidsts=document.getElementById('wsstate');"
"eidlog=document.getElementById('wslog');"
"eiderr=document.getElementById('wserr');"
"eidcnt=document.getElementById('wscnt');"
"var connection = new WebSocket(wsurl);\n"
  "connection.onopen    = function()     { eidsts.innerHTML='Open'; connection.send('Connect ' + new Date());};\n"
  "connection.onerror   = function(error){ eidsts.innerHTML='ERROR'; eiderr.innerHTML=' '+error+' ';};\n"
  "connection.onmessage = function(e)\n"
  "{\n"
    "eidlog=document.getElementById('wslog');\n"
    "eidlog.innerHTML+=e.data+String.fromCharCode(10);\n"
    "eidcnt.innerHTML=i_cnt++;\n"
    "eiderr.innerHTML='';    \n"
   "}\n"
  "connection.onclose   = function()     { eidsts.innerHTML='CLOSED';};\n"
"</script>"
"</body></html>"
;
